version = 0.1

[default.deploy.parameters]
stack_name = "UltrasS3LambdaApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fhe9n733gxj7"
s3_prefix = "UltrasS3LambdaApp"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "UltrasS3StagingBucketName=\"ultras\" UltrasS3DevBucketName=\"ultras-dev\""
