AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates a Lambda function that writes to an S3 bucket

Globals:
  Function:
    Timeout: 20

Parameters:
  UltrasS3StagingBucketName:
    Type: String
  UltrasS3DevBucketName:
    Type: String

Resources:
  # Buckets
  UltrasS3StagingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref UltrasS3StagingBucketName
      AccessControl: BucketOwnerFullControl
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date
  UltrasS3DevBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref UltrasS3DevBucketName
      AccessControl: BucketOwnerFullControl
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - '*'
            ExposedHeaders:
              - Date

  # Lambda
  UltrasS3LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 1024
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      CodeUri: lambda/build/
      Handler: app.handler
      FunctionName: 'UltrasS3LambdaImageProcessingFunction'
      Policies:
        - AWSLambdaExecute
        - S3CrudPolicy:
            BucketName: !Ref UltrasS3StagingBucketName
        - S3CrudPolicy:
            BucketName: !Ref UltrasS3DevBucketName
      Events:
        CreateThumbnailStagingEvent:
          Type: S3
          Properties:
            Bucket: !Ref UltrasS3StagingBucket
            Events: s3:ObjectCreated:*
        CreateThumbnailDevEvent:
          Type: S3
          Properties:
            Bucket: !Ref UltrasS3DevBucket
            Events: s3:ObjectCreated:*

Outputs:
  UltrasS3StagingBucketName:
    Value: !Ref UltrasS3StagingBucketName
    Description: S3 Staging Bucket for object storage
  UltrasS3DevBucketName:
    Value: !Ref UltrasS3DevBucketName
    Description: S3 Dev Bucket for object storage
  FunctionArn:
    Value: !Ref UltrasS3LambdaFunction
    Description: UltrasS3LambdaFunction function Arn
