AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates a Lambda function that writes to an S3 bucket

Globals:
  Function:
    Timeout: 20

Parameters:
  UltrasS3BucketName:
    Type: String

Resources:
  # Bucket
  UltrasS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref UltrasS3BucketName
      AccessControl: BucketOwnerFullControl

  # # Bucket Policies
  # UltrasS3BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref UltrasS3BucketName
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Sid: PublicReadS3
  #           Effect: Allow
  #           Principal: '*'
  #           Action:
  #             - s3:GetObject
  #             - s3:GetObjectVersion
  #           Resource:
  #             - arn:aws:s3:::ultras/*

  # Lambda
  UltrasS3LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/build/
      Handler: app.handler
      Runtime: nodejs14.x
      Policies:
        - AWSLambdaExecute
        - S3CrudPolicy:
            BucketName: !Ref UltrasS3BucketName
      Architectures:
        - x86_64
      MemorySize: 1024
      Environment:
        Variables:
          ULTRAS_S3_BUCKET_NAME: !Ref UltrasS3BucketName
      Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref UltrasS3Bucket
            Events: s3:ObjectCreated:*

Outputs:
  UltrasS3BucketName:
    Value: !Ref UltrasS3BucketName
    Description: S3 Bucket for object storage
  FunctionArn:
    Value: !Ref UltrasS3LambdaFunction
    Description: UltrasS3LambdaFunction function Arn
