$RNFirebaseAsStaticFramework = true
$FirebaseSDKVersion = '9.4.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ultras' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  use_frameworks!

  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'ImageNotification' do
  pod 'Firebase/Messaging'

  use_frameworks!
end
