export type ColorKey =
  | 'transparent'
  | 'iconPrimary'
  | 'iconSecondary'
  | 'iconNavigation'
  | 'iconNotification'
  | 'iconUpdatesCount'
  | 'iconVerified'
  | 'backgroundMain'
  | 'backgroundCard'
  | 'backgroundCardInvert'
  | 'backgroundTabBar'
  | 'backgroundInput'
  | 'backgroundMessageSent'
  | 'backgroundMessageReceived'
  | 'backgroundMessageWarning'
  | 'backgroundLogo'
  | 'backgroundDivider'
  | 'backgroundDividerTransparent'
  | 'buttonPrimary'
  | 'buttonSecondary'
  | 'buttonAction'
  | 'buttonActionInvert'
  | 'textHeader'
  | 'textSectionHeader'
  | 'textAction'
  | 'textPrimary'
  | 'textSecondary'
  | 'textTertiary'
  | 'textQuaternary'
  | 'textQuinary'
  | 'textSenary'
  | 'textSeptenary'
  | 'textPrimaryInvert'
  | 'textSecondaryInvert'
  | 'textTertiaryInvert'
  | 'textQuaternaryInvert'
  | 'textQuinaryInvert'
  | 'textSenaryInvert'
  | 'textSeptenaryInvert';

export type ColorGroup<T extends string> = Record<T, string>;

export type ColorType = ColorGroup<ColorKey>;
