#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
cd "$(dirname "$0")/../" || exit 1

bash "$(dirname "$0")/_execute.sh" \
  --hook-command=pre-commit\
  --add-git-files-on-finish=true\
  --skip-check-changes=false\
  --continue-on-error=true\
  --ignore-missing-subpackage=true
